# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='users.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0busers.proto\"4\n\x08UserNote\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x16\n\x07message\x18\x02 \x01(\x0b\x32\x05.Chat\"1\n\x04\x43hat\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x19\n\x07\x63ontent\x18\x02 \x01(\x0b\x32\x08.Content\"9\n\x07\x43ontent\x12\r\n\x05nonce\x18\x01 \x01(\x0c\x12\x0b\n\x03tag\x18\x02 \x01(\x0c\x12\x12\n\nciphertext\x18\x03 \x01(\x0c\"\x18\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"\x1e\n\x0eNewUserRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\"+\n\x14RegistrationResponse\x12\x13\n\x0bisAvailable\x18\x01 \x01(\x08\"&\n\x0e\x41llOnlineUsers\x12\x14\n\x05users\x18\x01 \x01(\x0b\x32\x05.User\":\n\x0cOneOnOneChat\x12\x14\n\x05user1\x18\x01 \x01(\x0b\x32\x05.User\x12\x14\n\x05user2\x18\x02 \x01(\x0b\x32\x05.User\"\"\n\x07Warning\x12\x17\n\x0fwarning_message\x18\x01 \x01(\t2\x97\x02\n\x05Users\x12(\n\x0bSendMessage\x12\t.UserNote\x1a\x08.Warning\"\x00(\x01\x30\x01\x12\"\n\x0eStreamMessages\x12\x05.User\x1a\x05.Chat\"\x00\x30\x01\x12\x36\n\nCreateUser\x12\x0f.NewUserRequest\x1a\x15.RegistrationResponse\"\x00\x12-\n\x0eGetOnlineUsers\x12\x06.Empty\x1a\x0f.AllOnlineUsers\"\x00\x30\x01\x12\x39\n\x0f\x43onnectWithUser\x12\r.OneOnOneChat\x1a\x15.RegistrationResponse\"\x00\x12\x1e\n\x0c\x43heckRequest\x12\x05.User\x1a\x05.User\"\x00\x62\x06proto3')
)




_USERNOTE = _descriptor.Descriptor(
  name='UserNote',
  full_name='UserNote',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='UserNote.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='UserNote.message', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=67,
)


_CHAT = _descriptor.Descriptor(
  name='Chat',
  full_name='Chat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='Chat.sender', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='Chat.content', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=118,
)


_CONTENT = _descriptor.Descriptor(
  name='Content',
  full_name='Content',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nonce', full_name='Content.nonce', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag', full_name='Content.tag', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ciphertext', full_name='Content.ciphertext', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=177,
)


_USER = _descriptor.Descriptor(
  name='User',
  full_name='User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='User.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=203,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=212,
)


_NEWUSERREQUEST = _descriptor.Descriptor(
  name='NewUserRequest',
  full_name='NewUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='NewUserRequest.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=244,
)


_REGISTRATIONRESPONSE = _descriptor.Descriptor(
  name='RegistrationResponse',
  full_name='RegistrationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isAvailable', full_name='RegistrationResponse.isAvailable', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=289,
)


_ALLONLINEUSERS = _descriptor.Descriptor(
  name='AllOnlineUsers',
  full_name='AllOnlineUsers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='users', full_name='AllOnlineUsers.users', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=329,
)


_ONEONONECHAT = _descriptor.Descriptor(
  name='OneOnOneChat',
  full_name='OneOnOneChat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user1', full_name='OneOnOneChat.user1', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user2', full_name='OneOnOneChat.user2', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=389,
)


_WARNING = _descriptor.Descriptor(
  name='Warning',
  full_name='Warning',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='warning_message', full_name='Warning.warning_message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=425,
)

_USERNOTE.fields_by_name['message'].message_type = _CHAT
_CHAT.fields_by_name['content'].message_type = _CONTENT
_ALLONLINEUSERS.fields_by_name['users'].message_type = _USER
_ONEONONECHAT.fields_by_name['user1'].message_type = _USER
_ONEONONECHAT.fields_by_name['user2'].message_type = _USER
DESCRIPTOR.message_types_by_name['UserNote'] = _USERNOTE
DESCRIPTOR.message_types_by_name['Chat'] = _CHAT
DESCRIPTOR.message_types_by_name['Content'] = _CONTENT
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['NewUserRequest'] = _NEWUSERREQUEST
DESCRIPTOR.message_types_by_name['RegistrationResponse'] = _REGISTRATIONRESPONSE
DESCRIPTOR.message_types_by_name['AllOnlineUsers'] = _ALLONLINEUSERS
DESCRIPTOR.message_types_by_name['OneOnOneChat'] = _ONEONONECHAT
DESCRIPTOR.message_types_by_name['Warning'] = _WARNING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserNote = _reflection.GeneratedProtocolMessageType('UserNote', (_message.Message,), dict(
  DESCRIPTOR = _USERNOTE,
  __module__ = 'users_pb2'
  # @@protoc_insertion_point(class_scope:UserNote)
  ))
_sym_db.RegisterMessage(UserNote)

Chat = _reflection.GeneratedProtocolMessageType('Chat', (_message.Message,), dict(
  DESCRIPTOR = _CHAT,
  __module__ = 'users_pb2'
  # @@protoc_insertion_point(class_scope:Chat)
  ))
_sym_db.RegisterMessage(Chat)

Content = _reflection.GeneratedProtocolMessageType('Content', (_message.Message,), dict(
  DESCRIPTOR = _CONTENT,
  __module__ = 'users_pb2'
  # @@protoc_insertion_point(class_scope:Content)
  ))
_sym_db.RegisterMessage(Content)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
  DESCRIPTOR = _USER,
  __module__ = 'users_pb2'
  # @@protoc_insertion_point(class_scope:User)
  ))
_sym_db.RegisterMessage(User)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'users_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  ))
_sym_db.RegisterMessage(Empty)

NewUserRequest = _reflection.GeneratedProtocolMessageType('NewUserRequest', (_message.Message,), dict(
  DESCRIPTOR = _NEWUSERREQUEST,
  __module__ = 'users_pb2'
  # @@protoc_insertion_point(class_scope:NewUserRequest)
  ))
_sym_db.RegisterMessage(NewUserRequest)

RegistrationResponse = _reflection.GeneratedProtocolMessageType('RegistrationResponse', (_message.Message,), dict(
  DESCRIPTOR = _REGISTRATIONRESPONSE,
  __module__ = 'users_pb2'
  # @@protoc_insertion_point(class_scope:RegistrationResponse)
  ))
_sym_db.RegisterMessage(RegistrationResponse)

AllOnlineUsers = _reflection.GeneratedProtocolMessageType('AllOnlineUsers', (_message.Message,), dict(
  DESCRIPTOR = _ALLONLINEUSERS,
  __module__ = 'users_pb2'
  # @@protoc_insertion_point(class_scope:AllOnlineUsers)
  ))
_sym_db.RegisterMessage(AllOnlineUsers)

OneOnOneChat = _reflection.GeneratedProtocolMessageType('OneOnOneChat', (_message.Message,), dict(
  DESCRIPTOR = _ONEONONECHAT,
  __module__ = 'users_pb2'
  # @@protoc_insertion_point(class_scope:OneOnOneChat)
  ))
_sym_db.RegisterMessage(OneOnOneChat)

Warning = _reflection.GeneratedProtocolMessageType('Warning', (_message.Message,), dict(
  DESCRIPTOR = _WARNING,
  __module__ = 'users_pb2'
  # @@protoc_insertion_point(class_scope:Warning)
  ))
_sym_db.RegisterMessage(Warning)



_USERS = _descriptor.ServiceDescriptor(
  name='Users',
  full_name='Users',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=428,
  serialized_end=707,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendMessage',
    full_name='Users.SendMessage',
    index=0,
    containing_service=None,
    input_type=_USERNOTE,
    output_type=_WARNING,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StreamMessages',
    full_name='Users.StreamMessages',
    index=1,
    containing_service=None,
    input_type=_USER,
    output_type=_CHAT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateUser',
    full_name='Users.CreateUser',
    index=2,
    containing_service=None,
    input_type=_NEWUSERREQUEST,
    output_type=_REGISTRATIONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetOnlineUsers',
    full_name='Users.GetOnlineUsers',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_ALLONLINEUSERS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ConnectWithUser',
    full_name='Users.ConnectWithUser',
    index=4,
    containing_service=None,
    input_type=_ONEONONECHAT,
    output_type=_REGISTRATIONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CheckRequest',
    full_name='Users.CheckRequest',
    index=5,
    containing_service=None,
    input_type=_USER,
    output_type=_USER,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERS)

DESCRIPTOR.services_by_name['Users'] = _USERS

# @@protoc_insertion_point(module_scope)
